{\rtf1\ansi\ansicpg1252\cocoartf2636
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;\f1\fnil\fcharset0 .AppleColorEmojiUI;}
{\colortbl;\red255\green255\blue255;\red189\green198\blue208;}
{\*\expandedcolortbl;;\cssrgb\c78824\c81961\c85098;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs27\fsmilli13600 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 name: GitHub Actions Demo\
on: [push]\
jobs:\
  Explore-GitHub-Actions:\
    runs-on: ubuntu-latest\
    steps:\
      - run: echo "
\f1 \uc0\u55356 \u57225 
\f0  The job was automatically triggered by a $\{\{ github.event_name \}\} event."\
      - run: echo "
\f1 \uc0\u55357 \u56359 
\f0  This job is now running on a $\{\{ runner.os \}\} server hosted by GitHub!"\
      - run: echo "
\f1 \uc0\u55357 \u56590 
\f0  The name of your branch is $\{\{ github.ref \}\} and your repository is $\{\{ github.repository \}\}."\
      - name: Check out repository code\
        uses: actions/checkout@v2\
      - run: echo "
\f1 \uc0\u55357 \u56481 
\f0  The $\{\{ github.repository \}\} repository has been cloned to the runner."\
      - run: echo "
\f1 \uc0\u55357 \u56741 \u65039 
\f0  The workflow is now ready to test your code on the runner."\
      - name: List files in the repository\
        run: |\
          ls $\{\{ github.workspace \}\}\
      - run: echo "
\f1 \uc0\u55356 \u57167 
\f0  This job's status is $\{\{ job.status \}\}."\
}